from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

CLIENT_ROOT = Path("/home/ubuntu/reference-sources/telegram-web-a/src")
SERVER_ROOT = Path("/home/ubuntu/reference-sources/teamgram-server")
OUTPUT = Path("/home/ubuntu/IntelliGram/CLIENT_SERVER_RPC_CONTRACT.md")

CLIENT_EXTENSIONS = {".ts", ".tsx", ".js", ".jsx"}
SERVER_EXTENSIONS = {".go", ".proto", ".tl", ".md"}
REQUEST_PATTERN = re.compile(r"(?:new\s+)?GramJs\.([A-Za-z0-9_]+)\.([A-Za-z0-9_]+)")
HANDLER_FILE_PATTERN = re.compile(r"(?:^|/)([a-z]+)\.([A-Za-z0-9_]+)_handler\.go$")
CAMEL_BOUNDARY = re.compile(r"(?<!^)(?=[A-Z])")


def files_under(root: Path, extensions: set[str]):
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in extensions:
            yield path


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def to_method_key(namespace: str, name: str) -> str:
    return f"{namespace}.{name}"


def to_teamgram_key(namespace: str, name: str) -> str:
    return f"{namespace}.{name[:1].lower()}{name[1:]}"


def normalize_handler_namespace(value: str) -> str:
    return value.lower()


def main() -> None:
    client_usage: dict[str, set[str]] = defaultdict(set)
    for path in files_under(CLIENT_ROOT, CLIENT_EXTENSIONS):
        text = read(path)
        rel = str(path.relative_to(CLIENT_ROOT))
        for namespace, method in REQUEST_PATTERN.findall(text):
            client_usage[to_method_key(namespace, method)].add(rel)

    handler_files: dict[str, set[str]] = defaultdict(set)
    for path in files_under(SERVER_ROOT, {".go"}):
        rel = str(path.relative_to(SERVER_ROOT))
        match = HANDLER_FILE_PATTERN.search(rel)
        if match:
            namespace, method = match.groups()
            handler_files[f"{normalize_handler_namespace(namespace)}.{method}"].add(rel)

    server_text = "\n".join(read(path) for path in files_under(SERVER_ROOT, SERVER_EXTENSIONS))
    found_by_text: set[str] = set()
    missing: list[tuple[str, int, list[str]]] = []
    present_by_handler: list[tuple[str, int, list[str], list[str]]] = []
    ambiguous: list[tuple[str, int, list[str]]] = []

    for key, paths in sorted(client_usage.items()):
        namespace, method = key.split(".", 1)
        expected = to_teamgram_key(namespace, method)
        path_list = sorted(paths)
        direct_handlers = sorted(handler_files.get(expected, set()))
        if direct_handlers:
            present_by_handler.append((key, len(paths), path_list, direct_handlers))
        elif expected in server_text or key in server_text:
            found_by_text.add(key)
            ambiguous.append((key, len(paths), path_list))
        else:
            missing.append((key, len(paths), path_list))

    namespace_totals: dict[str, list[int]] = defaultdict(lambda: [0, 0, 0])
    for key, paths in client_usage.items():
        namespace = key.split(".", 1)[0]
        namespace_totals[namespace][0] += 1
        if any(item[0] == key for item in present_by_handler):
            namespace_totals[namespace][1] += 1
        elif key in found_by_text:
            namespace_totals[namespace][2] += 1

    lines = [
        "# Telegram Web A ↔ Teamgram RPC Contract Inventory",
        "",
        "This report is generated by statically scanning every JavaScript/TypeScript source file under Telegram Web A’s `src/` tree for GramJS API references and every Teamgram Go source file for named RPC handler files. It is a coverage map, not proof of end-to-end behavior: generated methods, aliases, feature gates, and handler internals require individual review.",
        "",
        f"**Distinct client-side GramJS references:** {len(client_usage):,}  ",
        f"**Directly matched Teamgram handler references:** {len(present_by_handler):,}  ",
        f"**Referenced in server source but not found as direct handler filenames:** {len(ambiguous):,}  ",
        f"**No static Teamgram reference found:** {len(missing):,}",
        "",
        "## Namespace summary",
        "",
        "| Namespace | Client methods | Direct handler matches | Text-only references | Unresolved by static filename/text scan |",
        "|---|---:|---:|---:|---:|",
    ]
    for namespace, values in sorted(namespace_totals.items()):
        total, direct, textual = values
        lines.append(f"| `{namespace}` | {total} | {direct} | {textual} | {total - direct - textual} |")

    lines.extend([
        "",
        "## Direct handler matches",
        "",
        "| Client RPC | Client source files | Teamgram handler files |",
        "|---|---:|---|",
    ])
    for key, count, _, handlers in present_by_handler:
        previews = "<br>".join(f"`{path}`" for path in handlers[:3])
        lines.append(f"| `{key}` | {count} | {previews} |")

    lines.extend([
        "",
        "## Text-only server references requiring manual confirmation",
        "",
        "| Client RPC | Client source files | Representative client paths |",
        "|---|---:|---|",
    ])
    for key, count, paths in ambiguous:
        previews = "<br>".join(f"`{path}`" for path in paths[:3])
        lines.append(f"| `{key}` | {count} | {previews} |")

    lines.extend([
        "",
        "## Unresolved client RPC references",
        "",
        "These methods were referenced by Telegram Web A but were not found in a Teamgram handler filename or text search. Some are expected to be platform features that IntelliGram will intentionally defer; every row remains an explicit compatibility obligation until classified.",
        "",
        "| Client RPC | Client source files | Representative client paths |",
        "|---|---:|---|",
    ])
    for key, count, paths in missing:
        previews = "<br>".join(f"`{path}`" for path in paths[:3])
        lines.append(f"| `{key}` | {count} | {previews} |")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
