import {readFileSync} from 'node:fs';

const source = readFileSync('client/src/lib/mtproto/schema.ts', 'utf8');
const marker = 'export default ';
const start = source.indexOf(marker);
if (start < 0) {
  throw new Error('Generated schema export was not found');
}
const exportValue = source.slice(start + marker.length).trim();
const assertion = exportValue.lastIndexOf('} as ');
if (assertion < 0) {
  throw new Error('Generated schema type assertion was not found');
}
const schema = JSON.parse(exportValue.slice(0, assertion + 1));
const wanted = new Set([
  'user',
  'userEmpty',
  'users.userFull',
  'userFull',
  'contacts.contacts',
  'messages.dialogs',
  'messages.dialogsSlice',
  'messages.peerDialogs',
  'messages.messages',
  'messages.messagesSlice',
  'message',
  'dialog',
  'peerUser',
  'peerChat',
  'inputPeerSelf',
  'inputPeerUser',
  'inputPeerChat',
  'inputUserSelf',
  'inputUser',
  'inputDialogPeer',
  'userStatusEmpty',
  'peerSettings',
  'peerNotifySettings',
  'privacyValueAllowAll',
  'account.privacyRules',
  'peerNotifySettings',
  'updateNewMessage',
  'updateMessageID',
  'updates',
  'updatesCombined',
  'updatesTooLong',
  'messages.invitedUsers',
  'chat',
  'chatEmpty',
  'updateNewChat',
  'updateChatParticipants',
  'chatParticipants',
  'chatPhotoEmpty',
  'inputFile',
  'inputFileBig',
  'photo',
  'photoEmpty',
  'photoSize',
  'photos.photo',
  'inputPhotoFileLocation',
  'upload.file',
  'storage.fileUnknown',
  'updates.difference',
  'updates.differenceEmpty',
  'chatFull',
  'messages.chatFull',
  'chatParticipants',
  'chatParticipant',
  'messages.affectedMessages',
  'messages.peerSettings',
  'auth.loggedOut',
  'updateShort',
  'updateUserTyping',
  'updateChatUserTyping',
  'langPackDifference',
  'help.countriesList',
  'help.countriesListNotModified',
  'contacts.resolvedPeer',
  'updateReadHistoryInbox',
  'updateChatParticipants',
  'updateEditMessage',
  'updateDeleteMessages',
  'contacts.importedContacts',
  'contacts.found',
  'importedContact',
  'inputPhoneContact',
]);
const wantedMethods = new Set([
  'users.getUsers',
  'users.getFullUser',
  'contacts.getContacts',
  'messages.getDialogs',
  'messages.getPeerDialogs',
  'messages.getHistory',
  'messages.sendMessage',
  'account.updateStatus',
  'account.getPrivacy',
  'messages.createChat',
  'account.updateProfile',
  'upload.saveFilePart',
  'upload.saveBigFilePart',
  'photos.uploadProfilePhoto',
  'upload.getFile',
  'updates.getDifference',
  'messages.getFullChat',
  'messages.readHistory',
  'messages.setTyping',
  'messages.getPeerSettings',
  'auth.logOut',
  'langpack.getLangPack',
  'help.getCountriesList',
  'contacts.resolveUsername',
  'messages.addChatUser',
  'messages.deleteChatUser',
  'messages.editChatTitle',
  'messages.editChatAbout',
  'messages.editMessage',
  'messages.deleteMessages',
  'messages.forwardMessages',
  'contacts.importContacts',
  'contacts.search',
]);
for (const entry of schema.API.constructors.filter((item) => wanted.has(item.predicate))) {
  console.log(JSON.stringify({kind: 'constructor', ...entry}, null, 2));
}
for (const entry of schema.API.methods.filter((item) => wantedMethods.has(item.method))) {
  console.log(JSON.stringify({kind: 'method', ...entry}, null, 2));
}
